### ISSUE TITLE
Bug - Breaks core Integration test

### ISSUE THREAD

**Issue by zaxkh** [magmodules/magento2-reloadify#10]
After installing this module via composer on Adobe Commerce 2.4.4, Integration Tests fail resulting with this error:

### Error:

```
There was 1 failure:

1) Magento\Webapi\Controller\Rest\SchemaRequestProcessorTest::testSchemaRequest with data set #0 ('rest/schema')
Failed asserting that '{"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-6318a69e7872f"}' matches PCRE pattern "/200 Success/".

/root/build/vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Webapi/Controller/Rest/SchemaRequestProcessorTest.php:27
/root/build/vendor/bin/phpunit:120

FAILURES!
Tests: 14, Assertions: 65, Failures: 1.

```

#### Install:
`composer require magmodules/magento2-reloadify`
`php bin/magento setup:upgrade`
`php bin/magento cache:flush`

#### Run Test:
`vendor/bin/phpunit -c $PWD/phpunit-integration.xml`

#### Add: -> To `Magento_Base_Dir/test/install-config-mysql.php`
```
    'disable-modules' => join(
        ',',
        [
            'Magmodules_Reloadify'
        ]
    ),
```

**Comment by Marvin-Magmodules** [comment]
Hi @zaxkh,

We are happy to share that we’ve just released the new [1.5.5](https://github.com/magmodules/magento2-reloadify/releases/tag/1.5.5) version where we have fixed this issue. Thank you for opening this issue and for the detailed feedback. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
