### ISSUE TITLE
Webapi Error: V1/reloadify/language/:store_id/products-delta

### ISSUE THREAD

**Issue by RakeshJesadiya** [magmodules/magento2-reloadify#18]
Magmodules Web API throws an error while using the latest **magmodules/magento2-reloadify:1.5.5** version.

I have tried to load the request URL and throws an error.

Action: GET

URL: https://magento2.test/rest/V1/reloadify/language/1/products-delta

Header: ADMIN TOKEN

The response should be proper product array data while currently throwing an error.

`
{
    "message": "Warning: Undefined array key 0 in /var/www/html/vendor/magmodules/magento2-reloadify/Service/WebApi/Product.php on line 198",
    "trace": "#0 /var/www/html/vendor/magmodules/magento2-reloadify/Service/WebApi/Product.php(198): Magento\\Framework\\App\\ErrorHandler->handler(2, 'Undefined array...', '/var/www/html/v...', 198)\n#1 /var/www/html/vendor/magmodules/magento2-reloadify/Service/WebApi/Product.php(166): Magmodules\\Reloadify\\Service\\WebApi\\Product->applyFilter(Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor), Array, 1)\n#2 /var/www/html/vendor/magmodules/magento2-reloadify/Service/WebApi/Product.php(100): Magmodules\\Reloadify\\Service\\WebApi\\Product->getCollection(1, Array, NULL)\n#3 /var/www/html/vendor/magmodules/magento2-reloadify/Model/WebApi/Repository.php(171): Magmodules\\Reloadify\\Service\\WebApi\\Product->execute(1, Array, NULL)\n#4 [internal function]: Magmodules\\Reloadify\\Model\\WebApi\\Repository->getProductsDelta(1, NULL)\n#5 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#6 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(195): 
}
`

**Comment by Marvin-Magmodules** [comment]
Hi @RakeshJesadiya

We are happy to share that we’ve just released the new [1.5.6](https://github.com/magmodules/magento2-reloadify/releases/tag/1.5.6) version where we have fixed this issue. Thank you for opening this issue and for the detailed issue report. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
